route:
  group_by: ['alertname', 'severity']  # Group by alert name and severity
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 15m
  receiver: 'telegram_info'  # Default receiver for non-categorized alerts
  routes:
    - match:
        severity: "critical"  # Alerts with severity "critical"
      receiver: 'telegram_critical'
    - match_re:
        severity: "info|warning|major"  # Alerts with severity "info", "warning", or "major"
      receiver: 'telegram_info'

receivers:
  - name: 'telegram_info'
    telegram_configs:
      - bot_token: '(your bot token)'
        chat_id: (your chat id)  # Chat ID for informational and non-critical alerts
        message: |
          {{ range .Alerts }}
          ✅ [{{ .Status }}] {{ .Labels.severity | toUpper }} - {{ .Labels.alertname }}
          *Description*: {{ .Annotations.description }}
          *Server*: "{{ .Annotations.server }}"
          {{ end }}

  - name: 'telegram_critical'
    telegram_configs:
      - bot_token: '(your bot token)'  # Token for the second bot
        chat_id: (your chat id)  # Chat ID for critical alerts
        message: |
          {{ range .Alerts }}
          🔴 [{{ .Status }}] CRITICAL - {{ .Labels.alertname }}
          *Description*: {{ .Annotations.description }}
          *Server*: "{{ .Annotations.server }}"
          {{ end }}
