{
 "title": "Avail Metrics Cumulo v3",
 "description": "This Grafana panel for Avail Node provides comprehensive visibility into the critical performance and status metrics of the node in the Avail network. ",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "node_version",
    "query": {
     "query": "query_result(substrate_build_info)"
    }
   },
   {
    "name": "moniker",
    "query": {
     "query": "query_result(substrate_build_info)"
    }
   },
   {
    "name": "chain",
    "query": {
     "query": "query_result(substrate_build_info)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n    <img src=\"https://cumulo.pro/images/pic09.png\" alt=\"Logo\" style=\"height: 150px;\"> <!-- Ajusta la altura según sea necesario -->\n    <h2>Avail Node metrics</h2>\n    <h5>by <a href=\"https://cumulo.pro\">Cumulo</a></h5>\n</div>\n"
   }
  },
  {
   "title": "Block Height",
   "type": "stat",
   "description": "- best: This is the most recent block that the node considers to be the best known block.\n- finalised: This is the last block that has been finalised and confirmed as a permanent part of the chain.\n- sync_target (sync target): This is the block height target that the node is trying to reach during synchronisation. ",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{job=\"$job\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Node Version",
   "type": "text",
   "description": "This metric provides static information about the build and network configuration of a Substrate-based node. This metric is useful for identifying the This metric provides static information about the build and network configuration of a Substrate-based node. This metric is useful for identifying the node's software version ",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "options": {
    "content": "<h3 style=\"color:#ADD8E6; font-size: 36px; text-align: center;\">\n  ${node_version}\n</h3>"
   },
   "targets": [
    {
     "expr": "substrate_build_info{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Moniker",
   "type": "text",
   "description": "This metric provides static information about the build and network configuration of a Substrate-based node. This metric is useful for identifying the node",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 9 },
   "options": {
    "content": "<h3 style=\"color: #ADD8E6; font-size: 36px; text-align: center;\">\n  ${moniker}\n</h3>"
   }
  },
  {
   "title": "Chain Id",
   "type": "text",
   "description": "Specifies the blockchain network the node is connected to.",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 9 },
   "options": {
    "content": "<h3 style=\"color: #ADD8E6; font-size: 36px; text-align: center;\">\n  ${chain}\n</h3>"
   }
  },
  {
   "title": "Node Role",
   "type": "stat",
   "description": "Indicates the roles the node is configured to perform within the network. The numeric value corresponds to a specific role or combination of roles the node is performing.\n•  0: None (No roles assigned)\n•  1: Full Node (Participates in block propagation but does not produce blocks)\n•  2: Light Client (Downloads only block headers and necessary state)\n•  4: Authority (Validator or other authority roles)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_node_roles{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Major Syncing",
   "type": "stat",
   "description": " This metric indicates whether the node is performing a major synchronisation or not. In a blockchain environment, a major synchronisation can refer to an intensive process where the node catches up with the entire blockchain, downloading and verifying all blocks from the genesis or from a significant fork.",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_is_major_syncing{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Start Time",
   "type": "stat",
   "description": "Timestamp indicating when the node process was last started",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - substrate_process_start_time_seconds{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Average Block Proposal Time",
   "type": "gauge",
   "description": "This metric measures the time it takes to build a block and prepare it for the proposal.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_proposer_block_proposal_time_sum{job=\"$job\"} / substrate_proposer_block_proposal_time_count{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Block Construction Time",
   "type": "gauge",
   "description": "Time it takes to build blocks in the network. This metric is useful for monitoring the efficiency of the block building process.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_proposer_block_constructed_sum{job=\"$job\"} / substrate_proposer_block_constructed_count{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Inherent Creation Time",
   "type": "gauge",
   "description": "This metric measures the average time it takes to execute the creation of inherents during block production. Inherents are special extrinsics that are added to blocks without requiring a transaction, such as timestamp updates or session key rotations.",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_proposer_create_inherents_time_sum{job=\"$job\"} / substrate_proposer_create_inherents_time_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Proposal End Reason: no more transactions",
   "type": "gauge",
   "description": "This metric tracks the reasons why block proposing was ended. It provides insight into the conditions under which the block production process completes.",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_proposer_end_proposal_reason{reason=\"no_more_transactions\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Transactions in the Queue",
   "type": "stat",
   "description": "Number of transactions that are in the queue of transactions ready to be included in a block.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_ready_transactions_number{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num blocks import queue",
   "type": "gauge",
   "description": "Number of blocks that are in the import queue on the chain.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sync_queued_blocks{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num transactions",
   "type": "stat",
   "description": "Number of transactions included in the most recent block in the network.",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_proposer_number_of_transactions{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Known Forks",
   "type": "stat",
   "description": "Measures the number of forks in the chain. An increase in the number of forks may indicate consensus problems or possible attacks on the network. Maintaining a low and stable number of forks is generally a sign of a healthy network.",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_number_leaves{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Import Queue Processed Total",
   "type": "timeseries",
   "description": "This metric is a counter that accumulates the total number of blocks the node has processed through the import queue. A higher value indicates that the node is actively processing blocks. Monitoring this metric can help track the node's performance and activity over time.\nUseful for ensuring the import queue is functioning properly and processing blocks without delays or failures. Anomalies, such as a stagnating value, might indicate issues in the queue or synchronization.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "substrate_import_queue_processed_total{job=\"$job\"}",
     "legendFormat": "Number of blocks the node has processed through the import queue"
    }
   ]
  },
  {
   "title": "Queued Blocks",
   "type": "timeseries",
   "description": "The current number of blocks that are in the import queue to be processed by the network. In the context of a blockchain, block import refers to the process of receiving, validating and adding new blocks to the main chain.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_sync_queued_blocks{job=\"$job\"}",
     "legendFormat": "num blocks"
    }
   ]
  },
  { "title": "Node Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Total Connected Peers",
   "type": "gauge",
   "description": "Total number of peers connected to the node, regardless of their role. This metric measures all active Libp2p connections, including those not directly participating in synchronization.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "peers Discoverd",
   "type": "gauge",
   "description": "Indicates the current number of nodes (or peers) that have been discovered and are stored in the peerset manager.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peerset_num_discovered{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Sync Peers",
   "type": "gauge",
   "description": "Number of active peers with which the node is currently synchronizing. This metric specifically measures the peers participating in the block synchronization process.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sync_peers{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Connections Handshake Errors",
   "type": "gauge",
   "description": "This metric tracks the total number of incoming Libp2p connections that failed during the initial handshake phase. Failures are categorized by their reason.\n•  limit-reached: Connection rejected because the node reached its maximum allowed number of connections.\n•  transport-error: Failure due to a transport-level error.",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_incoming_connections_handshake_errors_total{job=\"$job\"}",
     "legendFormat": "reason: {{reason}}"
    }
   ]
  },
  {
   "title": "Local Addresses Listening",
   "type": "gauge",
   "description": "This metric tracks the total number of local addresses where the node is actively listening for incoming Libp2p connections.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_listeners_local_addresses{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Connection Errors",
   "type": "gauge",
   "description": "This metric measures the total number of errors that occurred during the establishment of pending connections, categorized by the reason for the error.\n•\tinvalid-peer-id: Invalid peer ID.\n•\tlimit-reached: The limit of allowed connections has been reached.\n•\ttransport-error: Error in the transport layer, such as network failures or disconnections.",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_pending_connections_errors_total{job=\"$job\"}",
     "legendFormat": "Reason: {{reason}}"
    }
   ]
  },
  {
   "title": "Libp2p Distinct Peers Connections (Closed & Opened)",
   "type": "gauge",
   "description": "This metric indicates how many distinct peers have disconnected & node has successfully connected  from the node. A high value could result from frequent network rebalancing, churn, or instability.",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_distinct_peers_connections_closed_total{job=\"$job\"}",
     "legendFormat": "Connections Closed"
    },
    {
     "expr": "substrate_sub_libp2p_distinct_peers_connections_opened_total{job=\"$job\"}",
     "legendFormat": "Connections Opened"
    }
   ]
  },
  {
   "title": "RPC Sessions Closed & Open",
   "type": "gauge",
   "description": "This metric tracks the total number of persistent RPC (Remote Procedure Call) sessions that have been closed & open by the node. Low Value (0): Indicates that no sessions have been terminated, suggesting a stable connection.",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_rpc_sessions_closed{job=\"$job\"}",
     "legendFormat": "Sessions Closed"
    },
    {
     "expr": "substrate_rpc_sessions_opened{job=\"$job\"}",
     "legendFormat": "Sessions Opened"
    }
   ]
  },
  {
   "title": "Incoming Connections Total",
   "type": "timeseries",
   "description": "This metric tracks the rate of new connections on the node's listening sockets.\nThis metric measures the overall activity of incoming connections, helping to assess the node's exposure and interaction with peers.\nHigh Value: Indicates frequent connection attempts, suggesting active participation in the network.",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 49 },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_incoming_connections_total{job=\"$job\"}[5m])",
     "legendFormat": "Incoming connections "
    }
   ]
  },
  {
   "title": "Libp2p Distinct Peers Connections (Closed & Opened)",
   "type": "timeseries",
   "description": "This metric indicates how many distinct peers have disconnected & node has successfully connected  from the node. A high value could result from frequent network rebalancing, churn, or instability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_distinct_peers_connections_closed_total{job=\"$job\"}",
     "legendFormat": "Connections Closed with Distinct Peers"
    },
    {
     "expr": "substrate_sub_libp2p_distinct_peers_connections_opened_total{job=\"$job\"}",
     "legendFormat": "Connections Opened with Distinct Peers"
    }
   ]
  },
  {
   "title": "Pending Connections",
   "type": "timeseries",
   "description": "This metric measures the number of pending connections that are in the process of being established on the node using the Libp2p protocol.\nPending connections represent active attempts to establish communication with other nodes. This includes the initial negotiation time, such as the handshake and the configuration of the communication channel.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_pending_connections{job=\"$job\"}",
     "legendFormat": "Pending Connections"
    }
   ]
  },
  {
   "title": "Libp2p Connections Closed Total",
   "type": "timeseries",
   "description": "This metric tracks the total number of Libp2p connections that have been closed, categorized by direction and reason.\n\n•  keep-alive-timeout: Connection closed due to inactivity.\n•  ping-timeout: Connection closed because of an unresponsive peer.\n•  protocol-error: Connection closed because of a protocol violation.\n•  sync-notifications-clogged: Notifications queue overflowed.\n•  transport-error: Connection closed due to a transport-level error.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_connections_closed_total{job=\"$job\"}",
     "legendFormat": "reason: {{reason}}"
    }
   ]
  },
  {
   "title": "Listeners Errors Total",
   "type": "timeseries",
   "description": "This metric tracks the total number of non-fatal errors encountered by Libp2p listeners on the node. Low or Zero Value (0): Indicates stable operation with no non-fatal errors detected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_listeners_errors_total{job=\"$job\"}[5m])",
     "legendFormat": "non-fatal errors"
    }
   ]
  },
  {
   "title": "Transaction Propagation Rate",
   "type": "timeseries",
   "description": "This metric measures the rate of transaction propagation per second from the node to other peers in the blockchain network. It allows to analyze the continuous flow of transactions propagated in 5-minute intervals, providing a dynamic view of the node's efficiency and activity in the network.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "rate(substrate_sync_propagated_transactions{job=\"$job\"}[5m])",
     "legendFormat": "transaction propagation per second"
    }
   ]
  },
  {
   "title": "Libp2p Connections Opened Total",
   "type": "timeseries",
   "description": "This metric tracks the total number of Libp2p connections opened by the node, categorized by direction. Direction: Specifies whether the connection was inbound (in) or outbound (out)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_connections_opened_total{job=\"$job\"}",
     "legendFormat": "direction: {{direction}}"
    }
   ]
  },
  {
   "title": "Avail Node Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Task Polling Duration ",
   "type": "timeseries",
   "description": "Counts the total number of times the invocation of Future::poll has been started for each specific task. This helps to understand how often tasks are executed compared to the duration of their invocations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_duration_bucket{job=\"$job\"}[5m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Polling Rate Imbalance",
   "type": "timeseries",
   "description": "This composite metric is useful for monitoring system performance and efficiency, helping to identify processing problems and optimise the execution of tasks on the network. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_started_total{job=\"$job\"}[1m]) - rate(substrate_tasks_polling_duration_count[1m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Active Internal Broadcast Channels",
   "type": "timeseries",
   "description": "This metric tracks the number of active internal channels that are transmitting network events using the Libp2p protocol.\n\nname: Identifies the module associated to the channel.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_out_events_num_channels{job=\"$job\"}",
     "legendFormat": "Name: {{name}}"
    }
   ]
  },
  {
   "title": "Queued Blocks in Import Queue",
   "type": "timeseries",
   "description": "This metric measures the number of blocks currently in the node's import queue. The import queue is where received blocks wait to be processed and validated before being added to the local blockchain.",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 87 },
   "targets": [
    {
     "expr": "substrate_sync_queued_blocks{job=\"$job\"}",
     "legendFormat": "number of blocks currently in the node's import queue"
    }
   ]
  },
  {
   "title": "Issued Light Client Requests",
   "type": "gauge",
   "description": "This metric tracks how many requests the node has sent to light clients for synchronization or data retrieval. A value of 0 means no requests have been made, which may indicate that no light clients are connected or requesting data. An increasing value shows active communication with light clients.\nThis metric is useful for monitoring the node's interaction with light clients, especially in networks that prioritize lightweight synchronization and efficiency.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_issued_light_requests{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Mempool stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Transactions Pruned by Block Events",
   "type": "stat",
   "description": "This metric measures the total number of transactions removed from the mempool (transaction pool) due to block-related events.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_txpool_block_transactions_pruned{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Resubmitted by Block Events",
   "type": "stat",
   "description": "This metric measures the total number of transactions forwarded to the mempool due to block-related events.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_txpool_block_transactions_resubmitted{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool Transactions Submitted",
   "type": "stat",
   "description": "This metric measures the total number of transactions sent to the node's mempool.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_txpool_submitted_transactions{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Rate Validations Finished",
   "type": "timeseries",
   "description": "This metric measures the rate  total number of transactions that have completed the validation process in the mempool.\nNode Activity Indicator: A high volume of validations indicates that the node is actively processing transactions.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "rate(substrate_sub_txpool_validations_finished{job=\"$job\"}[5m])",
     "legendFormat": "Transactions "
    }
   ]
  },
  {
   "title": "Invalid Transactions Removed",
   "type": "timeseries",
   "description": "This metric measures the total number of transactions removed from the mempool because they were considered invalid during the validation process.\n\nDuring the validation process, transactions in the mempool are evaluated according to the rules of the blockchain protocol. If a transaction does not comply with these rules, it is marked as invalid and removed from the mempool.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 102 },
   "targets": [
    {
     "expr": "rate(substrate_sub_txpool_validations_invalid{job=\"$job\"}[5m])",
     "legendFormat": "Transactions "
    }
   ]
  },
  {
   "title": "Transactions Scheduled for Validation",
   "type": "timeseries",
   "description": "This metric measures the total number of transactions scheduled for the validation process in the mempool.\nThis metric tracks all transactions that have been entered into the mempool and have been scheduled to be validated. A scheduled transaction has not yet been processed, but is in the queue to determine its validity.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 102 },
   "targets": [
    {
     "expr": "rate(substrate_sub_txpool_validations_scheduled{job=\"$job\"}[5m])",
     "legendFormat": "Transactions "
    }
   ]
  },
  { "title": "GRANDPA ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "GRANDPA's gossip",
   "type": "timeseries",
   "description": "Information on the number of messages validated by the gossip validator of the GRANDPA (GHOST-based Recursive ANcestor Deriving Prefix Agreement) completion mechanism.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "substrate_finality_grandpa_communication_gossip_validator_messages{job=\"$job\"}",
     "legendFormat": "{{message}} : {{action}}"
    }
   ]
  },
  {
   "title": "Grandpa Prevotes Total",
   "type": "stat",
   "description": "Information on the total number of prevotes made locally by the GRANDPA (GHOST-based Recursive ANcestor Deriving Prefix Agreement) completion mechanism in the chain.\nThis metric is useful to monitor the activity and performance of the GRANDPA consensus process in the avail_turing_network chain, providing an indication of the total number of prevotes that have been issued by the validators.\n",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_finality_grandpa_prevotes_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Gossip Expired",
   "type": "stat",
   "description": "Total number of messages that have expired and have not been processed by the gossip service.\nA high number of expired messages may indicate network overload or problems in message processing, where messages are not handled before they expire.\n",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_network_gossip_expired_messages_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grandpa Finality Round",
   "type": "stat",
   "description": "Indicates the highest number of completed rounds using the GRANDPA (GHOST-based Recursive ANcestor Deriving Prefix Agreement) completion protocol.\nThis value can be used to monitor the progress of the network in terms of block completion. An increasing value indicates that the network is progressing and completing more rounds.",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_finality_grandpa_round{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grandpa Precommits Total",
   "type": "stat",
   "description": "The metric provides information on the total number of precommits made locally by the GRANDPA (GHOST-based Recursive ANcestor Deriving Prefix Agreement) completion mechanism in the chain.",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_finality_grandpa_precommits_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finality Grandpa Waiting Messages",
   "type": "timeseries",
   "description": "Indicates the number of GRANDPA (GHOST-based Recursive ANcestor Deriving Prefix Agreement) finality messages that are waiting in the \"until imported\" queue. These messages are pending processing before being imported into the node. An increasing value may signal delays or bottlenecks in message processing, which could be due to network congestion or node performance issues. Monitoring this metric helps ensure the efficient processing of finality messages and the smooth operation of the network's consensus protocol.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "substrate_finality_grandpa_until_imported_waiting_messages_number{job=\"$job\"}",
     "legendFormat": "Num Grandpa Waiting Messages"
    }
   ]
  },
  {
   "title": "Justification Import Time",
   "type": "timeseries",
   "description": "Indicates the time taken to import justifications in GRANDPA. This metric is critical for monitoring the performance of the node in processing finality proofs. Lower times indicate that justifications are being processed efficiently, which is essential for maintaining finality performance.\nThe metric categorizes the time taken into different buckets (le, or \"less than or equal to\") for specific thresholds in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "targets": [
    {
     "expr": "substrate_justification_import_time_bucket{job=\"$job\"}",
     "legendFormat": "bucket: {{le}}"
    }
   ]
  },
  { "title": "Authority Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "Failures Handling 'Value Found' Events in DHT",
   "type": "gauge",
   "description": "This metric shows the number of times the authority discovery system failed to handle a value_found event in the Distributed Hash Table (DHT). A failure in handling these events means that, although a requested value was found in the DHT, an error occurred during its processing.\nalue: 0 – Indicates that no failures have been recorded when handling value_found events so far.",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 128 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_authority_discovery_handle_value_found_event_failure{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Known Authorities Count",
   "type": "gauge",
   "description": "This metric shows the current number of authority nodes known to the authority discovery system in the network. Known authorities are nodes that have been identified and stored by the system, allowing for reliable connections and communication across the network.",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 128 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_authority_discovery_known_authorities_count{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Times External Addresses Published",
   "type": "gauge",
   "description": "This metric shows the total number of times the authority discovery system has published external addresses for the nodes in the network. Each publication event makes the node's external addresses available to other network participants, enhancing connectivity.\nIf this count is unusually low or stagnant, it might indicate issues with address publication, potentially affecting other nodes' ability to connect.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 128 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_authority_discovery_times_published_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Authority Address Requests",
   "type": "gauge",
   "description": "This metric shows the number of pending requests for authority addresses in the network. Pending requests represent attempts by nodes to obtain addresses of other authorized nodes (or “authorities”) in the network that have not yet been resolved.\n0 – This indicates that there are currently no pending requests for authority addresses in the network. \n",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 128 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_authority_discovery_authority_address_requests_pending{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHT Events Received by Authority Discovery",
   "type": "timeseries",
   "description": "This metric tracks the number of Distributed Hash Table (DHT) events received by the authority discovery system. Each event type represents different outcomes in DHT operations, such as successfully finding or storing values, which are essential for maintaining network connectivity.\nValues\n•\tvalue_found: 60,198 – The number of times a requested value was found in the DHT.\n•\tvalue_not_found: 2,928 – The number of times a requested value was not found in the DHT.\n•\tvalue_put: 10,023 – The number of times a value was successfully stored in the DHT.\n•\tvalue_put_failed: 5 – The number of times an attempt to store a value in the DHT failed.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 134 },
   "targets": [
    {
     "expr": "substrate_authority_discovery_dht_event_received{job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Justification Import Time",
   "type": "timeseries",
   "description": "Indicates the time taken to import justifications in GRANDPA. This metric is critical for monitoring the performance of the node in processing finality proofs. Lower times indicate that justifications are being processed efficiently, which is essential for maintaining finality performance.\nThe metric categorizes the time taken into different buckets (le, or \"less than or equal to\") for specific thresholds in seconds",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 134 },
   "targets": [
    {
     "expr": "substrate_justification_import_time_bucket{job=\"$job\"}",
     "legendFormat": "le: {{le}}"
    }
   ]
  },
  {
   "title": "External Addresses Last Published",
   "type": "timeseries",
   "description": "This metric provides the count of external addresses that were published the last time authority discovery updated addresses in the network. It shows the current number of addresses made available by the authority discovery mechanism, which helps other network participants connect and maintain communication with the node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "targets": [
    {
     "expr": "substrate_authority_discovery_amount_external_addresses_last_published{job=\"$job\"}",
     "legendFormat": "Number of External Addresses"
    }
   ]
  },
  {
   "title": "Total Authority Addresses Requested",
   "type": "timeseries",
   "description": "This metric shows the total number of times the authority discovery system has requested external addresses of a single authority node within the network. Each request represents an instance where the network attempted to retrieve the address information of a specific authority, which is essential for maintaining node connectivity.\nAn unexpectedly high or rapidly increasing count could indicate frequent address loss or issues with address retention, prompting more requests than usual. Monitoring this can help identify if connectivity problems are emerging.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "targets": [
    {
     "expr": "substrate_authority_discovery_authority_addresses_requested_total{job=\"$job\"}",
     "legendFormat": "total authority address requests."
    }
   ]
  },
  { "title": "State System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 150 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_build_info{job=\"$job\"}",
     "legendFormat": "Node: {{name}}  Version:   {{version}}  Chain:  {{chain}} "
    }
   ]
  },
  {
   "title": "State Cache",
   "type": "stat",
   "description": "Indicates the size of the state cache in bytes.",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_state_cache_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Bandwidth Usage ",
   "type": "stat",
   "description": "This metric indicates the total bandwidth usage of the libp2p network in bytes. This information is crucial for monitoring, optimising and ensuring network performance.",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_network_bytes_total{job=\"$job\"}",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Average execution time",
   "type": "timeseries",
   "description": "This metric measures the total execution time for the construction of the header extension, the time is reported in microseconds. This metric provides a clear view of the performance of the node in terms of total execution time for the header extension construction.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avail_header_extension_builder_total_execution_time_sum/avail_header_extension_builder_total_execution_time_count",
     "legendFormat": "Avail Node Microseconds (µs)"
    }
   ]
  },
  {
   "title": "Evaluation Grid Build Time",
   "type": "timeseries",
   "description": "This metric measures the average time required to build the header extension evaluation grid on an avail_turing_network node.  Building the evaluation grid\" refers to the creation of a data structure that organises and evaluates the information in the data block or transactions. This structure can be used for various purposes, including network validation, verification and optimisation.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avail_header_extension_builder_evaluation_grid_build_time_sum / avail_header_extension_builder_evaluation_grid_build_time_count",
     "legendFormat": "Avail Node Microseconds (µs)"
    }
   ]
  },
  {
   "title": "Average time to build commitment",
   "type": "timeseries",
   "description": "Average time to build the header extension commitment on a node in the avail_turing_network network.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avail_header_extension_builder_commitment_build_time_sum/avail_header_extension_builder_commitment_build_time_count",
     "legendFormat": "Avail Node Microseconds (µs)"
    }
   ]
  }
 ]
}