{
 "title": "Avail Metrics Cumulo v2",
 "description": "This Grafana panel for Avail Node provides comprehensive visibility into the critical performance and status metrics of the node in the Avail network. ",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n    <img src=\"https://cumulo.pro/images/pic09.png\" alt=\"Logo\" style=\"height: 150px;\"> <!-- Ajusta la altura según sea necesario -->\n    <h2>Avail Node metrics</h2>\n    <h5>by <a href=\"https://cumulo.pro\">Cumulo</a></h5>\n</div>\n"
   }
  },
  {
   "title": "Block Height",
   "type": "stat",
   "description": "- best: This is the most recent block that the node considers to be the best known block.\n- finalised: This is the last block that has been finalised and confirmed as a permanent part of the chain.\n- sync_target (sync target): This is the block height target that the node is trying to reach during synchronisation. ",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{job=\"$job\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Node metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Average Block Proposal Time",
   "type": "gauge",
   "description": "This metric measures the time it takes to build a block and prepare it for the proposal.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_proposer_block_proposal_time_sum{job=\"$job\"} / substrate_proposer_block_proposal_time_count{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Block Construction Time",
   "type": "gauge",
   "description": "Time it takes to build blocks in the network. This metric is useful for monitoring the efficiency of the block building process.",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_proposer_block_constructed_sum{job=\"$job\"} / substrate_proposer_block_constructed_count{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "peers Connected",
   "type": "gauge",
   "description": "Number of peers connected to the network",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "peers Discoverd",
   "type": "gauge",
   "description": "Indicates the current number of nodes (or peers) that have been discovered and are stored in the peerset manager.",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peerset_num_discovered{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Major Syncing",
   "type": "stat",
   "description": " This metric indicates whether the node is performing a major synchronisation or not. In a blockchain environment, a major synchronisation can refer to an intensive process where the node catches up with the entire blockchain, downloading and verifying all blocks from the genesis or from a significant fork.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_is_major_syncing{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num transactions",
   "type": "stat",
   "description": "Number of transactions included in the most recent block in the network.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_proposer_number_of_transactions{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Transactions in the Queue",
   "type": "stat",
   "description": "Number of transactions that are in the queue of transactions ready to be included in a block.",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_ready_transactions_number{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num blocks import queue",
   "type": "gauge",
   "description": "Number of blocks that are in the import queue on the chain.",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sync_queued_blocks{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queued Blocks",
   "type": "timeseries",
   "description": "The current number of blocks that are in the import queue to be processed by the network. In the context of a blockchain, block import refers to the process of receiving, validating and adding new blocks to the main chain.",
   "gridPos": { "h": 5, "w": 7, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_sync_queued_blocks{job=\"$job\"}",
     "legendFormat": "num blocks"
    }
   ]
  },
  {
   "title": "Number of Known Forks",
   "type": "stat",
   "description": "Measures the number of forks in the chain. An increase in the number of forks may indicate consensus problems or possible attacks on the network. Maintaining a low and stable number of forks is generally a sign of a healthy network.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_number_leaves{job=\"$job\"}"
    }
   ]
  },
  { "title": "State System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_build_info{job=\"$job\"}",
     "legendFormat": "Node: {{name}}  Version:   {{version}}  Chain:  {{chain}} "
    }
   ]
  },
  {
   "title": "State Cache",
   "type": "stat",
   "description": "Indicates the size of the state cache in bytes.",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_state_cache_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Bandwidth Usage ",
   "type": "stat",
   "description": "This metric indicates the total bandwidth usage of the libp2p network in bytes. This information is crucial for monitoring, optimising and ensuring network performance.",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_network_bytes_total{job=\"$job\"}",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Number of Nodes Discovered",
   "type": "timeseries",
   "description": "This metric indicates the number of discovered nodes that are stored in the peerset manager. This information is crucial for monitoring the node discovery process, optimising node performance and ensuring the overall health of the network.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peerset_num_discovered{job=\"$job\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Evaluation Grid Build Time",
   "type": "timeseries",
   "description": "This metric measures the average time required to build the header extension evaluation grid on an avail_turing_network node.  Building the evaluation grid\" refers to the creation of a data structure that organises and evaluates the information in the data block or transactions. This structure can be used for various purposes, including network validation, verification and optimisation.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avail_header_extension_builder_evaluation_grid_build_time_sum / avail_header_extension_builder_evaluation_grid_build_time_count",
     "legendFormat": "Avail Node Microseconds (µs)"
    }
   ]
  },
  {
   "title": "Average execution time",
   "type": "timeseries",
   "description": "This metric measures the total execution time for the construction of the header extension, the time is reported in microseconds. This metric provides a clear view of the performance of the node in terms of total execution time for the header extension construction.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avail_header_extension_builder_total_execution_time_sum/avail_header_extension_builder_total_execution_time_count",
     "legendFormat": "Avail Node Microseconds (µs)"
    }
   ]
  },
  {
   "title": "Average time to build commitment",
   "type": "timeseries",
   "description": "Average time to build the header extension commitment on a node in the avail_turing_network network.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avail_header_extension_builder_commitment_build_time_sum/avail_header_extension_builder_commitment_build_time_count",
     "legendFormat": "Avail Node Microseconds (µs)"
    }
   ]
  },
  {
   "title": "Avail Node Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Task Polling Duration ",
   "type": "timeseries",
   "description": "Counts the total number of times the invocation of Future::poll has been started for each specific task. This helps to understand how often tasks are executed compared to the duration of their invocations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_duration_bucket{job=\"$job\"}[5m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Polling Rate Imbalance",
   "type": "graph",
   "description": "This composite metric is useful for monitoring system performance and efficiency, helping to identify processing problems and optimise the execution of tasks on the network. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_started_total{job=\"$job\"}[1m]) - rate(substrate_tasks_polling_duration_count[1m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  { "title": "GRANDPA ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "GRANDPA's gossip",
   "type": "timeseries",
   "description": "Information on the number of messages validated by the gossip validator of the GRANDPA (GHOST-based Recursive ANcestor Deriving Prefix Agreement) completion mechanism.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "substrate_finality_grandpa_communication_gossip_validator_messages{job=\"$job\"}",
     "legendFormat": "{{message}} : {{action}}"
    }
   ]
  },
  {
   "title": "Grandpa Precommits Total",
   "type": "stat",
   "description": "The metric provides information on the total number of precommits made locally by the GRANDPA (GHOST-based Recursive ANcestor Deriving Prefix Agreement) completion mechanism in the chain.",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_finality_grandpa_precommits_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Gossip Expired",
   "type": "stat",
   "description": "Total number of messages that have expired and have not been processed by the gossip service.\nA high number of expired messages may indicate network overload or problems in message processing, where messages are not handled before they expire.\n",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_network_gossip_expired_messages_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grandpa Prevotes Total",
   "type": "stat",
   "description": "Information on the total number of prevotes made locally by the GRANDPA (GHOST-based Recursive ANcestor Deriving Prefix Agreement) completion mechanism in the chain.\nThis metric is useful to monitor the activity and performance of the GRANDPA consensus process in the avail_turing_network chain, providing an indication of the total number of prevotes that have been issued by the validators.\n",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_finality_grandpa_prevotes_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grandpa Finality Round",
   "type": "stat",
   "description": "Indicates the highest number of completed rounds using the GRANDPA (GHOST-based Recursive ANcestor Deriving Prefix Agreement) completion protocol.\nThis value can be used to monitor the progress of the network in terms of block completion. An increasing value indicates that the network is progressing and completing more rounds.",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_finality_grandpa_round{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}